#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConteoCiudadano
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CC")]
	public partial class ConteoCiudadanoDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertActa(Acta instance);
    partial void UpdateActa(Acta instance);
    partial void DeleteActa(Acta instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertCandidato(Candidato instance);
    partial void UpdateCandidato(Candidato instance);
    partial void DeleteCandidato(Candidato instance);
    partial void InsertPartido(Partido instance);
    partial void UpdatePartido(Partido instance);
    partial void DeletePartido(Partido instance);
    partial void InsertTranscripcion(Transcripcion instance);
    partial void UpdateTranscripcion(Transcripcion instance);
    partial void DeleteTranscripcion(Transcripcion instance);
    #endregion
		
		public ConteoCiudadanoDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CCConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConteoCiudadanoDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConteoCiudadanoDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConteoCiudadanoDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConteoCiudadanoDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Acta> Actas
		{
			get
			{
				return this.GetTable<Acta>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Candidato> Candidatos
		{
			get
			{
				return this.GetTable<Candidato>();
			}
		}
		
		public System.Data.Linq.Table<Partido> Partidos
		{
			get
			{
				return this.GetTable<Partido>();
			}
		}
		
		public System.Data.Linq.Table<Transcripcion> Transcripcions
		{
			get
			{
				return this.GetTable<Transcripcion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Acta")]
	public partial class Acta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nombre;
		
		private int _ID;
		
		private System.Nullable<int> _Transcripciones;
		
		private EntitySet<Transcripcion> _Transcripcions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTranscripcionesChanging(System.Nullable<int> value);
    partial void OnTranscripcionesChanged();
    #endregion
		
		public Acta()
		{
			this._Transcripcions = new EntitySet<Transcripcion>(new Action<Transcripcion>(this.attach_Transcripcions), new Action<Transcripcion>(this.detach_Transcripcions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transcripciones", DbType="Int")]
		public System.Nullable<int> Transcripciones
		{
			get
			{
				return this._Transcripciones;
			}
			set
			{
				if ((this._Transcripciones != value))
				{
					this.OnTranscripcionesChanging(value);
					this.SendPropertyChanging();
					this._Transcripciones = value;
					this.SendPropertyChanged("Transcripciones");
					this.OnTranscripcionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Acta_Transcripcion", Storage="_Transcripcions", ThisKey="ID", OtherKey="ActaID")]
		public EntitySet<Transcripcion> Transcripcions
		{
			get
			{
				return this._Transcripcions;
			}
			set
			{
				this._Transcripcions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transcripcions(Transcripcion entity)
		{
			this.SendPropertyChanging();
			entity.Acta = this;
		}
		
		private void detach_Transcripcions(Transcripcion entity)
		{
			this.SendPropertyChanging();
			entity.Acta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nick;
		
		private string _email;
		
		private string _Password;
		
		private int _ID;
		
		private EntitySet<Transcripcion> _Transcripcions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNickChanging(string value);
    partial void OnNickChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public Usuario()
		{
			this._Transcripcions = new EntitySet<Transcripcion>(new Action<Transcripcion>(this.attach_Transcripcions), new Action<Transcripcion>(this.detach_Transcripcions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nick", DbType="NVarChar(50)")]
		public string Nick
		{
			get
			{
				return this._Nick;
			}
			set
			{
				if ((this._Nick != value))
				{
					this.OnNickChanging(value);
					this.SendPropertyChanging();
					this._Nick = value;
					this.SendPropertyChanged("Nick");
					this.OnNickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(120)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(20)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Transcripcion", Storage="_Transcripcions", ThisKey="ID", OtherKey="UsuarioID")]
		public EntitySet<Transcripcion> Transcripcions
		{
			get
			{
				return this._Transcripcions;
			}
			set
			{
				this._Transcripcions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transcripcions(Transcripcion entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Transcripcions(Transcripcion entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Candidato")]
	public partial class Candidato : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Candidato1;
		
		private int _ID;
		
		private EntitySet<Partido> _Partidos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCandidato1Changing(string value);
    partial void OnCandidato1Changed();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public Candidato()
		{
			this._Partidos = new EntitySet<Partido>(new Action<Partido>(this.attach_Partidos), new Action<Partido>(this.detach_Partidos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Candidato", Storage="_Candidato1", DbType="NVarChar(50)")]
		public string Candidato1
		{
			get
			{
				return this._Candidato1;
			}
			set
			{
				if ((this._Candidato1 != value))
				{
					this.OnCandidato1Changing(value);
					this.SendPropertyChanging();
					this._Candidato1 = value;
					this.SendPropertyChanged("Candidato1");
					this.OnCandidato1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Candidato_Partido", Storage="_Partidos", ThisKey="ID", OtherKey="CandidatoID")]
		public EntitySet<Partido> Partidos
		{
			get
			{
				return this._Partidos;
			}
			set
			{
				this._Partidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Partidos(Partido entity)
		{
			this.SendPropertyChanging();
			entity.Candidato = this;
		}
		
		private void detach_Partidos(Partido entity)
		{
			this.SendPropertyChanging();
			entity.Candidato = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Partido")]
	public partial class Partido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nombre;
		
		private System.Nullable<int> _CandidatoID;
		
		private EntityRef<Candidato> _Candidato;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCandidatoIDChanging(System.Nullable<int> value);
    partial void OnCandidatoIDChanged();
    #endregion
		
		public Partido()
		{
			this._Candidato = default(EntityRef<Candidato>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(20)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidatoID", DbType="Int")]
		public System.Nullable<int> CandidatoID
		{
			get
			{
				return this._CandidatoID;
			}
			set
			{
				if ((this._CandidatoID != value))
				{
					if (this._Candidato.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCandidatoIDChanging(value);
					this.SendPropertyChanging();
					this._CandidatoID = value;
					this.SendPropertyChanged("CandidatoID");
					this.OnCandidatoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Candidato_Partido", Storage="_Candidato", ThisKey="CandidatoID", OtherKey="ID", IsForeignKey=true)]
		public Candidato Candidato
		{
			get
			{
				return this._Candidato.Entity;
			}
			set
			{
				Candidato previousValue = this._Candidato.Entity;
				if (((previousValue != value) 
							|| (this._Candidato.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Candidato.Entity = null;
						previousValue.Partidos.Remove(this);
					}
					this._Candidato.Entity = value;
					if ((value != null))
					{
						value.Partidos.Add(this);
						this._CandidatoID = value.ID;
					}
					else
					{
						this._CandidatoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Candidato");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transcripcion")]
	public partial class Transcripcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _FechaHora;
		
		private System.Nullable<int> _UsuarioID;
		
		private System.Nullable<int> _PAN;
		
		private System.Nullable<int> _PRI;
		
		private System.Nullable<int> _PRD;
		
		private System.Nullable<int> _VERDE;
		
		private System.Nullable<int> _PT;
		
		private System.Nullable<int> _MC;
		
		private System.Nullable<int> _NA;
		
		private System.Nullable<int> _PRI_VERDE;
		
		private System.Nullable<int> _PRD_PT_MC;
		
		private System.Nullable<int> _PRD_PT;
		
		private System.Nullable<int> _PRD_MC;
		
		private System.Nullable<int> _PT_MC;
		
		private System.Nullable<int> _NR;
		
		private System.Nullable<int> _VN;
		
		private System.Nullable<int> _TOTAL;
		
		private System.Nullable<int> _ActaID;
		
		private int _ID;
		
		private EntityRef<Acta> _Acta;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFechaHoraChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaHoraChanged();
    partial void OnUsuarioIDChanging(System.Nullable<int> value);
    partial void OnUsuarioIDChanged();
    partial void OnPANChanging(System.Nullable<int> value);
    partial void OnPANChanged();
    partial void OnPRIChanging(System.Nullable<int> value);
    partial void OnPRIChanged();
    partial void OnPRDChanging(System.Nullable<int> value);
    partial void OnPRDChanged();
    partial void OnVERDEChanging(System.Nullable<int> value);
    partial void OnVERDEChanged();
    partial void OnPTChanging(System.Nullable<int> value);
    partial void OnPTChanged();
    partial void OnMCChanging(System.Nullable<int> value);
    partial void OnMCChanged();
    partial void OnNAChanging(System.Nullable<int> value);
    partial void OnNAChanged();
    partial void OnPRI_VERDEChanging(System.Nullable<int> value);
    partial void OnPRI_VERDEChanged();
    partial void OnPRD_PT_MCChanging(System.Nullable<int> value);
    partial void OnPRD_PT_MCChanged();
    partial void OnPRD_PTChanging(System.Nullable<int> value);
    partial void OnPRD_PTChanged();
    partial void OnPRD_MCChanging(System.Nullable<int> value);
    partial void OnPRD_MCChanged();
    partial void OnPT_MCChanging(System.Nullable<int> value);
    partial void OnPT_MCChanged();
    partial void OnNRChanging(System.Nullable<int> value);
    partial void OnNRChanged();
    partial void OnVNChanging(System.Nullable<int> value);
    partial void OnVNChanged();
    partial void OnTOTALChanging(System.Nullable<int> value);
    partial void OnTOTALChanged();
    partial void OnActaIDChanging(System.Nullable<int> value);
    partial void OnActaIDChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public Transcripcion()
		{
			this._Acta = default(EntityRef<Acta>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaHora", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaHora
		{
			get
			{
				return this._FechaHora;
			}
			set
			{
				if ((this._FechaHora != value))
				{
					this.OnFechaHoraChanging(value);
					this.SendPropertyChanging();
					this._FechaHora = value;
					this.SendPropertyChanged("FechaHora");
					this.OnFechaHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", DbType="Int")]
		public System.Nullable<int> UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAN", DbType="Int")]
		public System.Nullable<int> PAN
		{
			get
			{
				return this._PAN;
			}
			set
			{
				if ((this._PAN != value))
				{
					this.OnPANChanging(value);
					this.SendPropertyChanging();
					this._PAN = value;
					this.SendPropertyChanged("PAN");
					this.OnPANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRI", DbType="Int")]
		public System.Nullable<int> PRI
		{
			get
			{
				return this._PRI;
			}
			set
			{
				if ((this._PRI != value))
				{
					this.OnPRIChanging(value);
					this.SendPropertyChanging();
					this._PRI = value;
					this.SendPropertyChanged("PRI");
					this.OnPRIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRD", DbType="Int")]
		public System.Nullable<int> PRD
		{
			get
			{
				return this._PRD;
			}
			set
			{
				if ((this._PRD != value))
				{
					this.OnPRDChanging(value);
					this.SendPropertyChanging();
					this._PRD = value;
					this.SendPropertyChanged("PRD");
					this.OnPRDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERDE", DbType="Int")]
		public System.Nullable<int> VERDE
		{
			get
			{
				return this._VERDE;
			}
			set
			{
				if ((this._VERDE != value))
				{
					this.OnVERDEChanging(value);
					this.SendPropertyChanging();
					this._VERDE = value;
					this.SendPropertyChanged("VERDE");
					this.OnVERDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT", DbType="Int")]
		public System.Nullable<int> PT
		{
			get
			{
				return this._PT;
			}
			set
			{
				if ((this._PT != value))
				{
					this.OnPTChanging(value);
					this.SendPropertyChanging();
					this._PT = value;
					this.SendPropertyChanged("PT");
					this.OnPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC", DbType="Int")]
		public System.Nullable<int> MC
		{
			get
			{
				return this._MC;
			}
			set
			{
				if ((this._MC != value))
				{
					this.OnMCChanging(value);
					this.SendPropertyChanging();
					this._MC = value;
					this.SendPropertyChanged("MC");
					this.OnMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NA", DbType="Int")]
		public System.Nullable<int> NA
		{
			get
			{
				return this._NA;
			}
			set
			{
				if ((this._NA != value))
				{
					this.OnNAChanging(value);
					this.SendPropertyChanging();
					this._NA = value;
					this.SendPropertyChanged("NA");
					this.OnNAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRI_VERDE", DbType="Int")]
		public System.Nullable<int> PRI_VERDE
		{
			get
			{
				return this._PRI_VERDE;
			}
			set
			{
				if ((this._PRI_VERDE != value))
				{
					this.OnPRI_VERDEChanging(value);
					this.SendPropertyChanging();
					this._PRI_VERDE = value;
					this.SendPropertyChanged("PRI_VERDE");
					this.OnPRI_VERDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRD_PT_MC", DbType="Int")]
		public System.Nullable<int> PRD_PT_MC
		{
			get
			{
				return this._PRD_PT_MC;
			}
			set
			{
				if ((this._PRD_PT_MC != value))
				{
					this.OnPRD_PT_MCChanging(value);
					this.SendPropertyChanging();
					this._PRD_PT_MC = value;
					this.SendPropertyChanged("PRD_PT_MC");
					this.OnPRD_PT_MCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRD_PT", DbType="Int")]
		public System.Nullable<int> PRD_PT
		{
			get
			{
				return this._PRD_PT;
			}
			set
			{
				if ((this._PRD_PT != value))
				{
					this.OnPRD_PTChanging(value);
					this.SendPropertyChanging();
					this._PRD_PT = value;
					this.SendPropertyChanged("PRD_PT");
					this.OnPRD_PTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRD_MC", DbType="Int")]
		public System.Nullable<int> PRD_MC
		{
			get
			{
				return this._PRD_MC;
			}
			set
			{
				if ((this._PRD_MC != value))
				{
					this.OnPRD_MCChanging(value);
					this.SendPropertyChanging();
					this._PRD_MC = value;
					this.SendPropertyChanged("PRD_MC");
					this.OnPRD_MCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PT_MC", DbType="Int")]
		public System.Nullable<int> PT_MC
		{
			get
			{
				return this._PT_MC;
			}
			set
			{
				if ((this._PT_MC != value))
				{
					this.OnPT_MCChanging(value);
					this.SendPropertyChanging();
					this._PT_MC = value;
					this.SendPropertyChanged("PT_MC");
					this.OnPT_MCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR", DbType="Int")]
		public System.Nullable<int> NR
		{
			get
			{
				return this._NR;
			}
			set
			{
				if ((this._NR != value))
				{
					this.OnNRChanging(value);
					this.SendPropertyChanging();
					this._NR = value;
					this.SendPropertyChanged("NR");
					this.OnNRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VN", DbType="Int")]
		public System.Nullable<int> VN
		{
			get
			{
				return this._VN;
			}
			set
			{
				if ((this._VN != value))
				{
					this.OnVNChanging(value);
					this.SendPropertyChanging();
					this._VN = value;
					this.SendPropertyChanged("VN");
					this.OnVNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Int")]
		public System.Nullable<int> TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this.OnTOTALChanging(value);
					this.SendPropertyChanging();
					this._TOTAL = value;
					this.SendPropertyChanged("TOTAL");
					this.OnTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActaID", DbType="Int")]
		public System.Nullable<int> ActaID
		{
			get
			{
				return this._ActaID;
			}
			set
			{
				if ((this._ActaID != value))
				{
					if (this._Acta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnActaIDChanging(value);
					this.SendPropertyChanging();
					this._ActaID = value;
					this.SendPropertyChanged("ActaID");
					this.OnActaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Acta_Transcripcion", Storage="_Acta", ThisKey="ActaID", OtherKey="ID", IsForeignKey=true)]
		public Acta Acta
		{
			get
			{
				return this._Acta.Entity;
			}
			set
			{
				Acta previousValue = this._Acta.Entity;
				if (((previousValue != value) 
							|| (this._Acta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Acta.Entity = null;
						previousValue.Transcripcions.Remove(this);
					}
					this._Acta.Entity = value;
					if ((value != null))
					{
						value.Transcripcions.Add(this);
						this._ActaID = value.ID;
					}
					else
					{
						this._ActaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Acta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Transcripcion", Storage="_Usuario", ThisKey="UsuarioID", OtherKey="ID", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Transcripcions.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Transcripcions.Add(this);
						this._UsuarioID = value.ID;
					}
					else
					{
						this._UsuarioID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
